version: '3.5'

services:
  sqlserver:
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword!
    ports:
      - '1433:1433'
    volumes:
      - ./mnt/data:/var/opt/mssql/data
      - ./mnt/log:/var/opt/mssql/log
      - ./mnt/secrets:/var/opt/mssql/secrets
